"""Load and apply learned feed overrides.

Cached in-memory for performance. Reads JSON files generated by overrides_learner.
"""

import os
import json
from typing import Dict, Any

MODELS_DIR = os.path.join(os.path.dirname(__file__), "..", "learn", "models")

_cache: Dict[str, Dict[str, Any]] = {}


def load_overrides(machine_id: str) -> Dict[str, Any] | None:
    """
    Load learned overrides for a machine.

    Returns None if no trained model exists.
    Caches in memory for performance.
    """
    if machine_id in _cache:
        return _cache[machine_id]

    path = os.path.join(MODELS_DIR, f"overrides_{machine_id}.json")
    if not os.path.exists(path):
        return None

    with open(path, "r", encoding="utf-8") as f:
        _cache[machine_id] = json.load(f)

    return _cache[machine_id]


def feed_factor_for_move(m: Dict[str, Any], machine_id: str) -> float:
    """
    Get learned feed multiplier for a move.

    Args:
        m: Move dictionary with keys: code, meta (slowdown, trochoid), radius_mm, etc.
        machine_id: Machine profile ID

    Returns:
        Feed multiplier (0.5-1.0). Returns 1.0 if no rule applies.

    Examples:
        - Tight arc (G2, radius=3mm, r_min=5mm): returns 0.75 (if learned)
        - Trochoid move: returns 0.85 (if learned)
        - Regular G1 move: returns 1.0
    """
    ov = load_overrides(machine_id)
    if not ov:
        return 1.0

    rules = ov.get("rules", {})
    meta = m.get("meta", {})
    code = m.get("code")

    # Tight arc?
    if code in ("G2", "G3"):
        rad = m.get("radius_mm") or 1e9  # large default if missing
        for k, v in rules.items():
            if k.startswith("arc_tight_mm<="):
                rmax = float(k.split("<=")[1])
                if rad <= rmax:
                    return float(v)

    # Trochoid?
    if meta.get("trochoid") and "trochoid" in rules:
        return float(rules["trochoid"])

    return 1.0
