"""
Generate badges.json and small SVG badges summarizing helical G-code size per preset.
Intended for GitHub Pages or local dashboard.

Usage:
    python tools/gen_helical_badge.py

Reads from: reports/helical_smoke_posts.json (generated by smoke test)
Outputs to: reports/badges/*.svg and reports/badges/badges.json

Color scheme:
    - red: No output or error
    - yellow: < 5 segments (minimal path)
    - green: 5-19 segments (typical)
    - blue: 20+ segments (complex path)
"""

import json
import pathlib

# Paths relative to project root
data_file = pathlib.Path("reports/helical_smoke_posts.json")
out_dir = pathlib.Path("reports/badges")
out_dir.mkdir(parents=True, exist_ok=True)

# Check if smoke test results exist
if not data_file.exists():
    print("❌ No helical_smoke_posts.json found; run smoke-helix-posts first.")
    print(f"   Expected location: {data_file.absolute()}")
    exit(1)

# Load smoke test results
try:
    results = json.load(open(data_file, encoding="utf-8"))
except Exception as e:
    print(f"❌ Failed to parse {data_file}: {e}")
    exit(1)

# Generate badge data
badges = {}
for name, info in results.items():
    bytes_ = info.get("bytes", 0)
    segments = info.get("segments", 0)
    arc_mode = info.get("arc_mode", "?")
    
    # Determine badge color based on complexity
    color = "#d73a4a"  # red (error/no output)
    if bytes_ > 0:
        if segments < 5:
            color = "#dbab09"  # yellow (minimal)
        elif segments < 20:
            color = "#28a745"  # green (typical)
        else:
            color = "#0366d6"  # blue (complex)
    
    badges[name] = {
        "bytes": bytes_,
        "segments": segments,
        "arc_mode": arc_mode,
        "color": color
    }

# Write combined badges.json
badges_json_path = out_dir / "badges.json"
with open(badges_json_path, "w", encoding="utf-8") as f:
    json.dump(badges, f, indent=2)

print(f"✅ Wrote {badges_json_path}")

# SVG badge template (shields.io style)
TEMPLATE = """<svg xmlns="http://www.w3.org/2000/svg" width="120" height="20">
  <linearGradient id="b" x2="0" y2="100%">
    <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
    <stop offset="1" stop-opacity=".1"/>
  </linearGradient>
  <clipPath id="a">
    <rect width="120" height="20" rx="3" fill="#fff"/>
  </clipPath>
  <g clip-path="url(#a)">
    <path fill="#555" d="M0 0h70v20H0z"/>
    <path fill="{color}" d="M70 0h50v20H70z"/>
    <path fill="url(#b)" d="M0 0h120v20H0z"/>
  </g>
  <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
    <text x="35" y="15" fill="#010101" fill-opacity=".3">{name}</text>
    <text x="35" y="14">{name}</text>
    <text x="95" y="15" fill="#010101" fill-opacity=".3">{bytes}b</text>
    <text x="95" y="14">{bytes}b</text>
  </g>
</svg>"""

# Generate individual SVG badges
svg_count = 0
for name, badge_data in badges.items():
    svg = TEMPLATE.format(
        name=name,
        bytes=badge_data["bytes"],
        color=badge_data["color"]
    )
    svg_path = out_dir / f"{name}.svg"
    with open(svg_path, "w", encoding="utf-8") as f:
        f.write(svg)
    svg_count += 1
    print(f"✅ Generated {svg_path.name} ({badge_data['bytes']} bytes, {badge_data['segments']} segments)")

print(f"\n🎉 Generated {svg_count} SVG badges + badges.json in {out_dir}")
print(f"   Total presets: {len(badges)}")
print(f"   Color breakdown:")
for name, badge_data in badges.items():
    color_name = {
        "#d73a4a": "red (error)",
        "#dbab09": "yellow (minimal)",
        "#28a745": "green (typical)",
        "#0366d6": "blue (complex)"
    }.get(badge_data["color"], "unknown")
    print(f"     {name}: {color_name} - {badge_data['bytes']}b, {badge_data['segments']} segs, {badge_data['arc_mode']} mode")
