"""SVG and DXF R12 rendering for modern rosette pattern paths."""
from __future__ import annotations

from typing import List

from .pattern_schemas import PathSegment


def export_paths_to_dxf(paths: List[PathSegment]) -> str:
    """Export paths to DXF R12 format."""
    lines = []
    lines.extend([
        "0", "SECTION",
        "2", "HEADER",
        "9", "$ACADVER",
        "1", "AC1009",
        "9", "$INSUNITS",
        "70", "4",
        "0", "ENDSEC",
    ])
    lines.extend(["0", "SECTION", "2", "TABLES", "0", "TABLE", "2", "LAYER"])
    layers = set(p.layer for p in paths)
    for layer in layers:
        lines.extend(
            ["0", "LAYER", "2", layer, "70", "0", "62", "7", "6", "CONTINUOUS"]
        )
    lines.extend(["0", "ENDTAB", "0", "ENDSEC"])
    lines.extend(["0", "SECTION", "2", "ENTITIES"])

    for path in paths:
        if len(path.points) < 2:
            continue
        if path.is_closed and len(path.points) >= 3:
            lines.extend(
                ["0", "POLYLINE", "8", path.layer, "66", "1", "70", "1"]
            )
            for pt in path.points:
                lines.extend([
                    "0", "VERTEX",
                    "8", path.layer,
                    "10", f"{pt.x:.6f}",
                    "20", f"{pt.y:.6f}",
                ])
            lines.extend(["0", "SEQEND"])
        else:
            for i in range(len(path.points) - 1):
                p1, p2 = path.points[i], path.points[i + 1]
                lines.extend([
                    "0", "LINE",
                    "8", path.layer,
                    "10", f"{p1.x:.6f}",
                    "20", f"{p1.y:.6f}",
                    "11", f"{p2.x:.6f}",
                    "21", f"{p2.y:.6f}",
                ])
    lines.extend(["0", "ENDSEC", "0", "EOF"])
    return "\n".join(lines)


def export_paths_to_svg(
    paths: List[PathSegment],
    title: str = "Rosette Pattern",
) -> str:
    """Export paths to SVG format."""
    all_x = [p.x for path in paths for p in path.points]
    all_y = [p.y for path in paths for p in path.points]
    if not all_x:
        min_x, max_x, min_y, max_y = -50, 50, -50, 50
    else:
        min_x, max_x = min(all_x), max(all_x)
        min_y, max_y = min(all_y), max(all_y)
    padding = 5
    width = max_x - min_x + 2 * padding
    height = max_y - min_y + 2 * padding

    svg_lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<svg xmlns="http://www.w3.org/2000/svg" ',
        f'     viewBox="{min_x - padding} {min_y - padding} {width} {height}"',
        f'     width="{width}mm" height="{height}mm">',
        f"  <title>{title}</title>",
        "  <desc>Generated by The Production Shop</desc>",
    ]
    for path in paths:
        if len(path.points) < 2:
            continue
        points_str = " ".join(f"{p.x:.3f},{p.y:.3f}" for p in path.points)
        if path.is_closed:
            svg_lines.append(
                f'  <polygon points="{points_str}" '
                f'fill="none" stroke="{path.color}" stroke-width="0.2"/>'
            )
        else:
            svg_lines.append(
                f'  <polyline points="{points_str}" '
                f'fill="none" stroke="{path.color}" stroke-width="0.2"/>'
            )
    svg_lines.append("</svg>")
    return "\n".join(svg_lines)


__all__ = [
    "export_paths_to_dxf",
    "export_paths_to_svg",
]
