#!/usr/bin/env python3
"""Render TEST_RUNTIME_CENSUS.md from TEST_RUNTIME_CENSUS.json (VECTORIZER-CI-BOUNDARY-001).

The JSON is the machine-readable source; the Markdown tables are derived from it.
`--check` exits 1 if the committed Markdown differs from a fresh render.
Measurements are not re-run here: they come from the CI log and the local probe
runs recorded in the JSON.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
BUNDLE = REPO_ROOT / "docs" / "investigations" / "vectorizer-ci-boundary_2026-10-03"
SOURCE = BUNDLE / "TEST_RUNTIME_CENSUS.json"
TARGET = BUNDLE / "TEST_RUNTIME_CENSUS.md"


def _num(value) -> str:
    if value is None:
        return "—"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, int):
        return f"{value:,}"
    if isinstance(value, float):
        return f"{value:,.1f}"
    return str(value)


def render(census: dict) -> str:
    env = census["environments"]
    obs = census["large_count_observation"]
    out = [
        "# Test runtime census",
        "",
        "<!-- Generated by scripts/investigations/generate_vectorizer_ci_boundary.py "
        "from TEST_RUNTIME_CENSUS.json. Do not edit by hand. -->",
        "",
        f"**Base:** `{census['base_sha']}`. **CI source:** {env['ci']['source']}. "
        f"**Local source:** {env['local']['source']}.",
        "",
        "## The ~266k observation",
        "",
        f"**Producer:** {obs['producer_summary']}",
        "",
        f"{obs['explanation']}",
        "",
        "## Evidence table",
        "",
        "Entity counts are `LINE` entities written by `EdgeToDXF` (CI: the `Created N LINE entities` "
        "log line; local: the probe's `line_count`). Times are the test's own duration. "
        "Peak memory is local only (CI does not report it).",
        "",
        "| ID | Test | Source fixture | Fixture | Calls | Entities (CI) | Entities (local) "
        "| Time CI (s) | Time local (s) | Peak local (MB) | Output (bytes, local) | Default CI before | After |",
        "|---|---|---|---|---|---:|---:|---:|---:|---:|---:|---|---|",
    ]
    for t in census["tests"]:
        out.append(
            f"| {t['id']} | `{t['test_id']}` | `{t['source_fixture']}` | {t['fixture_origin']} "
            f"| {t['calls']} | {_num(t['entity_count']['ci'])} | {_num(t['entity_count']['local'])} "
            f"| {_num(t['time_s']['ci'])} | {_num(t['time_s']['local'])} | {_num(t['peak_mb_local'])} "
            f"| {_num(t['output_bytes_local'])} | {_num(t['default_ci_before'])} "
            f"| {t['after']} |"
        )
    out += ["", "## Dispositions", "", "| ID | Disposition |", "|---|---|"]
    for t in census["tests"]:
        out.append(f"| {t['id']} | {t['disposition']} |")
    out += ["", "## Findings", "", "| ID | Finding | Action in this increment |", "|---|---|---|"]
    for f in census["findings"]:
        out.append(f"| {f['id']} | {f['finding']} | {f['action']} |")
    after = census.get("after_change_local")
    if after:
        out += ["", "## After the change — dedicated suite, local", "",
                f"{after['source']}", "",
                "| Measure | Before (5 tests, separate processes) | After (one dedicated run) |",
                "|---|---:|---:|"]
        for row in after["rows"]:
            out.append(f"| {row['measure']} | {_num(row['before'])} | {_num(row['after'])} |")
    dc = census["default_ci"]
    out += [
        "",
        "## Default-CI selection",
        "",
        f"- Expression before: {dc['expression_before']}",
        f"- Expression after: `{dc['expression_after']}`",
        f"- Excluded from default CI ({len(dc['excluded'])}):",
        *[f"  - `{x}`" for x in dc["excluded"]],
        f"- Collected by the dedicated workflow ({len(dc['dedicated'])}): the same set.",
        "",
    ]
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the Markdown is stale")
    args = parser.parse_args(argv)
    rendered = render(json.loads(SOURCE.read_text(encoding="utf-8")))
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(f"STALE: {TARGET.relative_to(REPO_ROOT)} differs from a fresh render", file=sys.stderr)
            return 1
        print("OK: census Markdown matches its JSON source")
        return 0
    TARGET.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
