"""initial schema from sqlite

Revision ID: 42a488dcbc25
Revises: 0001_supabase_auth
Create Date: 2026-03-29 17:40:29.559204

Source: ``docs/SQLITE_SCHEMA_AUDIT_2026_03_28.json`` — art_studio.db (rosette_*)
and cam_logs.db (runs, segments). rmos.sqlite had no tables; skipped.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a488dcbc25'
down_revision: Union[str, None] = '0001_supabase_auth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rosette_compare_risk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id_a', sa.Text(), nullable=False),
    sa.Column('job_id_b', sa.Text(), nullable=False),
    sa.Column('lane', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('diff_json', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rosette_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('preset', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('rosette_presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('pattern_type', sa.Text(), nullable=False),
    sa.Column('segments', sa.Integer(), nullable=False),
    sa.Column('inner_radius', sa.Float(), nullable=False),
    sa.Column('outer_radius', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_utc', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.Text(), nullable=True),
    sa.Column('machine_id', sa.Text(), nullable=True),
    sa.Column('material_id', sa.Text(), nullable=True),
    sa.Column('tool_d', sa.Float(), nullable=True),
    sa.Column('stepover', sa.Float(), nullable=True),
    sa.Column('stepdown', sa.Float(), nullable=True),
    sa.Column('post_id', sa.Text(), nullable=True),
    sa.Column('feed_xy', sa.Float(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('est_time_s', sa.Float(), nullable=True),
    sa.Column('act_time_s', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('len_mm', sa.Float(), nullable=True),
    sa.Column('limit', sa.Text(), nullable=True),
    sa.Column('slowdown', sa.Float(), nullable=True),
    sa.Column('trochoid', sa.Integer(), nullable=True),
    sa.Column('radius_mm', sa.Float(), nullable=True),
    sa.Column('feed_f', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'idx', name='uq_segments_run_idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segments')
    op.drop_table('runs')
    op.drop_table('rosette_presets')
    op.drop_table('rosette_jobs')
    op.drop_table('rosette_compare_risk')
    # ### end Alembic commands ###
