"""init

Revision ID: bd61b4204c35
Revises: 
Create Date: 2025-12-17 14:47:54.215715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd61b4204c35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('session_json', sa.Text(), nullable=False),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=True),
    sa.Column('material_id', sa.String(length=128), nullable=True),
    sa.Column('machine_id', sa.String(length=128), nullable=True),
    sa.Column('candidate_attempt_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_sessions')
    # ### end Alembic commands ###
