<script setup lang="ts">
/**
 * DiagnosticSnapshotExportMetadataCard — Export metadata display
 *
 * Dev Order 41: Displays snapshot export package metadata.
 *
 * Observational only — does NOT track download events, persist state,
 * or indicate actual export occurred.
 */
import type { DiagnosticSnapshotExportMetadata } from '@/types/diagnosticSnapshot'

const props = defineProps<{
  metadata: DiagnosticSnapshotExportMetadata
  warnings?: string[]
}>()

function formatTimestamp(iso: string): string {
  const date = new Date(iso)
  if (isNaN(date.getTime())) return 'Invalid'
  return date.toLocaleString()
}

function formatExportStatus(status: string): string {
  switch (status) {
    case 'prepared_not_exported':
      return 'Prepared (not exported)'
    case 'exported_json':
      return 'Exported as JSON'
    default:
      return status
  }
}
</script>

<template>
  <div :class="$style.card">
    <div :class="$style.header">
      <span :class="$style.label">Export Metadata</span>
    </div>

    <div :class="$style.metadata">
      <div :class="$style.metaItem">
        <span :class="$style.metaLabel">Schema Version</span>
        <span :class="$style.metaValue">{{ metadata.schemaVersion }}</span>
      </div>
      <div :class="$style.metaItem">
        <span :class="$style.metaLabel">Kind</span>
        <span :class="$style.metaValue">{{ metadata.kind }}</span>
      </div>
      <div :class="$style.metaItem">
        <span :class="$style.metaLabel">Generated By</span>
        <span :class="$style.metaValue">{{ metadata.generatedBy }}</span>
      </div>
      <div :class="$style.metaItem">
        <span :class="$style.metaLabel">Export Status</span>
        <span :class="$style.metaValue">{{ formatExportStatus(metadata.exportStatus) }}</span>
      </div>
      <div :class="$style.metaItem">
        <span :class="$style.metaLabel">Prepared At</span>
        <span :class="$style.metaValue">{{ formatTimestamp(metadata.exportPreparedAtIso) }}</span>
      </div>
    </div>

    <!-- Export Warnings -->
    <div v-if="warnings && warnings.length > 0" :class="$style.warnings">
      <span :class="$style.warningsLabel">Export Warnings</span>
      <div v-for="(warning, idx) in warnings" :key="idx" :class="$style.warning">
        {{ warning }}
      </div>
    </div>

    <!-- Notice -->
    <div :class="$style.notice">
      Export metadata describes the snapshot package only. It does not indicate persistence,
      restore, or calibration.
    </div>
  </div>
</template>

<style module>
.card {
  background: #111827;
  border: 1px solid #30363d;
  border-radius: 0.375rem;
  padding: 0.625rem;
}

.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 0.375rem;
  padding-bottom: 0.375rem;
  border-bottom: 1px solid #30363d;
}

.label {
  font-size: 0.8125rem;
  font-weight: 500;
  color: #d1d5db;
}

.metadata {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 0.375rem;
  margin-bottom: 0.375rem;
  padding: 0.375rem;
  background: rgba(55, 65, 81, 0.4);
  border-radius: 0.25rem;
}

.metaItem {
  display: flex;
  flex-direction: column;
  gap: 0.125rem;
}

.metaLabel {
  font-size: 0.5625rem;
  color: #6b7280;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.metaValue {
  font-size: 0.6875rem;
  font-weight: 500;
  color: #d1d5db;
  font-family: var(--font-mono, ui-monospace, monospace);
}

.warnings {
  margin-bottom: 0.5rem;
  padding: 0.375rem 0.5rem;
  background: rgba(251, 191, 36, 0.1);
  border-radius: 0.25rem;
}

.warningsLabel {
  display: block;
  font-size: 0.5625rem;
  color: #fbbf24;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  margin-bottom: 0.25rem;
}

.warning {
  font-size: 0.625rem;
  color: #fbbf24;
  margin-bottom: 0.125rem;
}

.warning:last-child {
  margin-bottom: 0;
}

.notice {
  padding: 0.375rem 0.5rem;
  background: rgba(107, 114, 128, 0.1);
  border-radius: 0.25rem;
  font-size: 0.6875rem;
  color: #9ca3af;
}
</style>
