"""
CP-S57 — Saw G-Code Models

Data models for saw-based CNC operations G-code generation.
Supports slice, batch, and contour operations with multi-pass depth control.

Key Models:
- SawToolpath: Single 2D cutting path
- DepthPass: Z-level for multi-pass operations
- SawGCodeRequest: Input parameters for G-code generation
- SawGCodeResult: Generated G-code with metadata

Usage:
```python
from cam_core.gcode.gcode_models import SawGCodeRequest, SawToolpath

request = SawGCodeRequest(
    op_type="slice",
    toolpaths=[SawToolpath(points=[(0, 0), (100, 0)], is_closed=False)],
    total_depth_mm=3.0,
    doc_per_pass_mm=1.0,
    feed_ipm=60,
    plunge_ipm=20
)
```
"""

from __future__ import annotations
from typing import List, Literal, Tuple
from pydantic import BaseModel, Field

Point2D = Tuple[float, float]  # (x, y) in mm

OpType = Literal["slice", "batch", "contour"]


class SawToolpath(BaseModel):
    """
    Single 2D cutting path for saw operations.
    
    Represents one continuous path to be cut at each depth level.
    For slice operations: straight line
    For batch operations: multiple parallel lines
    For contour operations: closed polygon or open curve
    """
    points: List[Point2D] = Field(
        ...,
        description="Ordered list of (x, y) points in mm",
        min_items=2
    )
    is_closed: bool = Field(
        default=False,
        description="Whether path forms closed loop (returns to start)"
    )


class DepthPass(BaseModel):
    """
    Single Z-level for multi-pass depth operations.
    
    Represents one incremental depth cut. Negative values indicate
    depth below surface (Z=0).
    """
    depth_mm: float = Field(
        ...,
        description="Z depth in mm (negative = below surface)"
    )


class SawGCodeRequest(BaseModel):
    """
    Request for generating saw operation G-code.
    
    Generic request supporting slice, batch, and contour operations.
    Handles multi-pass depth control, feed/speed parameters, and
    safe entry/exit moves.
    """
    op_type: OpType = Field(
        ...,
        description="Operation type: 'slice' (single cut), 'batch' (parallel cuts), 'contour' (closed shapes)"
    )

    # Geometry
    toolpaths: List[SawToolpath] = Field(
        ...,
        description="List of 2D cutting paths",
        min_items=1
    )

    # Depth / Stock
    total_depth_mm: float = Field(
        ...,
        description="Total depth into stock (positive value, will be negated for Z moves)",
        gt=0
    )
    doc_per_pass_mm: float = Field(
        ...,
        description="Maximum depth of cut per pass (step-down)",
        gt=0
    )

    # Feeds / Speeds
    feed_ipm: float = Field(
        ...,
        description="Cutting feed rate in inches per minute (IPM)",
        gt=0
    )
    plunge_ipm: float = Field(
        ...,
        description="Plunge feed rate in inches per minute (IPM)",
        gt=0
    )
    rapid_ipm: float = Field(
        default=200.0,
        description="Effective rapid rate (for documentation/comments only)",
        gt=0
    )

    # Z Reference
    safe_z_mm: float = Field(
        default=5.0,
        description="Clearance height above stock surface (mm)",
        ge=0
    )
    surface_z_mm: float = Field(
        default=0.0,
        description="Stock surface Z coordinate (typically 0)"
    )
    machine_units: Literal["mm", "inch"] = Field(
        default="mm",
        description="Machine units for feed rate conversion"
    )

    # Program Metadata
    program_id: str = Field(
        default="SAW_JOB",
        description="Program identifier for CNC controller"
    )
    program_comment: str = Field(
        default="Generated by Luthier's ToolBox Saw Lab",
        description="Comment line in G-code header"
    )

    # Operation Options
    climb_cut: bool = Field(
        default=False,
        description="Use climb milling (vs conventional) for contour ops"
    )
    closed_paths_only: bool = Field(
        default=False,
        description="Validate that all paths are closed (safety check for contour ops)"
    )


class SawGCodeResult(BaseModel):
    """
    Generated G-code with operation metadata.
    
    Contains complete G-code program ready for CNC execution,
    plus summary statistics for preview/validation.
    """
    gcode: str = Field(
        ...,
        description="Complete G-code program text"
    )
    op_type: OpType = Field(
        ...,
        description="Operation type (echoed from request)"
    )
    depth_passes: List[DepthPass] = Field(
        ...,
        description="Computed depth levels for multi-pass operation"
    )
    total_length_mm: float = Field(
        ...,
        description="Total cutting path length across all passes (mm)",
        ge=0
    )
