name: Bug report
description: File a bug report
labels: [bug]
body:
  - type: textarea
    id: desc
    attributes: { label: Description, description: "What happened? What did you expect?" }
    validations: { required: true }
  - type: textarea
    id: steps
    attributes: { label: Reproduction steps, description: "Minimal steps to reproduce" }
  - type: input
    id: version
    attributes: { label: Version / Patch tag }
  - type: textarea
    id: logs
    attributes: { label: Logs / screenshots }
