name: Feature request
description: Propose a feature
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes: { label: What problem does this solve? }
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes: { label: Proposal / Sketch / Mock } 
  - type: textarea
    id: impact
    attributes: { label: Impact / Risks }
