"""
Saw Lab 2.0 - Heat Calculator (Thermodynamic Model)

Calculates heat buildup risk using thermodynamic principles
rather than bucket factors.

Physics model:
    Heat is generated by:
    1. Chip formation work: Pc = Kc * MRR
    2. Friction between blade flanks and kerf walls

    Heat partition:
    - Fraction to chip (carried away): ~60-80% at high speeds
    - Fraction to workpiece: ~10-25%
    - Fraction to blade: ~5-15%

    Temperature rise at the cut surface:
        dT = q * delta / k
    where:
        q: heat flux to workpiece (W/m^2)
        delta: thermal penetration depth = sqrt(alpha * tc)
        k: thermal conductivity (W/m/K)
        alpha: thermal diffusivity = k / (rho * cp)
        tc: contact time per tooth pass

    Burn risk increases when:
    - Feed per tooth is very low (rubbing, not cutting)
    - Rim speed is very high (friction heating)
    - Material thermal conductivity is low (heat cannot escape)
    - No dust collection (hot chips re-contact surface)
"""
from __future__ import annotations

import math
from math import pi

from ..models import SawContext, SawDesign, SawCalculatorResult, MaterialProperties


# Heat partition fractions (typical for wood at moderate speeds)
_CHIP_FRACTION = 0.70
_WORKPIECE_FRACTION = 0.20
_BLADE_FRACTION = 0.10

# Temperature thresholds for wood (degrees C above ambient)
_TEMP_SAFE = 80.0        # < 80 C rise: no risk
_TEMP_CAUTION = 140.0    # 80-140 C: caution, possible discoloration
_TEMP_BURN = 200.0       # 140-200 C: burn marks likely
# > 200 C: charring / fire risk

# Minimum feed per tooth before rubbing regime (mm/tooth)
_MIN_FEED_PER_TOOTH_MM = 0.02


class SawHeatCalculator:
    """
    Calculates heat buildup feasibility using thermodynamic model.

    Uses cutting power, heat partition, and material thermal properties
    to estimate temperature rise at the cut surface.

    Factors:
        - Cutting power (from specific cutting energy * MRR)
        - Heat partition to workpiece
        - Material thermal properties (conductivity, specific heat, density)
        - Contact time (kerf width / rim speed)
        - Feed per tooth (rubbing detection)
        - Dust collection (chip evacuation)
    """

    def calculate(
        self,
        design: SawDesign,
        ctx: SawContext,
        material: MaterialProperties | None = None,
    ) -> SawCalculatorResult:
        """
        Calculate heat buildup score using thermodynamic model.

        Args:
            design: Cut design parameters
            ctx: Saw context
            material: Optional material properties

        Returns:
            SawCalculatorResult with temperature estimate
        """
        try:
            # --- Material properties ---
            kc = 30.0
            density = 700.0
            cp = 1700.0
            k_thermal = 0.15
            burn_tendency = 0.5
            if material is not None:
                kc = material.specific_cutting_energy_j_per_mm3
                density = material.density_kg_per_m3
                cp = material.specific_heat_capacity_j_per_kgk
                k_thermal = material.thermal_conductivity_w_per_mk
                burn_tendency = material.burn_tendency

            # --- MRR and cutting power ---
            if design.dado_width_mm > 0:
                cut_width = design.dado_width_mm
                cut_depth = design.dado_depth_mm
            else:
                cut_width = ctx.blade_kerf_mm
                cut_depth = ctx.stock_thickness_mm

            feed_rate_mm_per_s = ctx.feed_rate_mm_per_min / 60.0
            mrr_mm3_per_s = cut_width * cut_depth * feed_rate_mm_per_s
            cutting_power_w = kc * mrr_mm3_per_s

            # --- Heat to workpiece ---
            heat_to_workpiece_w = cutting_power_w * _WORKPIECE_FRACTION

            # --- Contact geometry ---
            rim_speed_mm_per_s = (pi * ctx.blade_diameter_mm * ctx.max_rpm) / 60.0
            if rim_speed_mm_per_s > 0:
                contact_time_s = ctx.blade_kerf_mm / rim_speed_mm_per_s
            else:
                contact_time_s = 0.01

            # Contact area: kerf * cut_depth (cross-section of cut surface)
            contact_area_mm2 = ctx.blade_kerf_mm * cut_depth
            contact_area_m2 = contact_area_mm2 * 1e-6

            # --- Temperature rise estimate ---
            # Heat flux to workpiece surface
            if contact_area_m2 > 0:
                heat_flux_w_per_m2 = heat_to_workpiece_w / contact_area_m2
            else:
                heat_flux_w_per_m2 = 0.0

            # Thermal diffusivity: alpha = k / (rho * cp)
            thermal_diffusivity_m2_per_s = k_thermal / (density * cp)

            # Penetration depth during contact: delta = sqrt(alpha * tc)
            if contact_time_s > 0:
                penetration_m = math.sqrt(thermal_diffusivity_m2_per_s * contact_time_s)
            else:
                penetration_m = 1e-6

            # Temperature rise: dT = q * delta / k
            # (1D transient conduction into semi-infinite solid)
            if k_thermal > 0:
                temp_rise_c = heat_flux_w_per_m2 * penetration_m / k_thermal
            else:
                temp_rise_c = 0.0

            # --- Feed per tooth check (rubbing detection) ---
            feed_per_tooth = ctx.feed_rate_mm_per_min / (ctx.max_rpm * ctx.tooth_count)
            rubbing = feed_per_tooth < _MIN_FEED_PER_TOOTH_MM

            # Rubbing amplifies heat (friction without cutting)
            if rubbing:
                temp_rise_c *= 1.5

            # Burn tendency amplifier
            temp_rise_c *= (1.0 + burn_tendency * 0.3)

            # Dust collection reduces heat (chips carry heat away)
            if not ctx.use_dust_collection:
                temp_rise_c *= 1.15

            # --- Scoring ---
            if temp_rise_c <= _TEMP_SAFE:
                score = 100.0
                warning = None
            elif temp_rise_c <= _TEMP_CAUTION:
                score = 75.0
                warning = (
                    f"Moderate heat risk: ~{temp_rise_c:.0f} C rise. "
                    f"Possible surface discoloration."
                )
            elif temp_rise_c <= _TEMP_BURN:
                score = 45.0
                warning = (
                    f"High heat risk: ~{temp_rise_c:.0f} C rise. "
                    f"Burn marks likely. Increase feed rate or reduce RPM."
                )
            else:
                score = 15.0
                warning = (
                    f"Critical heat: ~{temp_rise_c:.0f} C rise. "
                    f"Charring/fire risk. Reduce speed and increase feed immediately."
                )

            # Extra penalty for rubbing regime
            if rubbing and score > 30:
                score = max(30.0, score - 20.0)
                rub_msg = (
                    f" Feed/tooth {feed_per_tooth:.4f} mm is below cutting threshold; "
                    f"blade is rubbing, not cutting."
                )
                warning = (warning or "") + rub_msg

            return SawCalculatorResult(
                calculator_name="heat",
                score=round(score, 1),
                warning=warning if warning else None,
                metadata={
                    "temp_rise_c": round(temp_rise_c, 1),
                    "cutting_power_w": round(cutting_power_w, 1),
                    "heat_to_workpiece_w": round(heat_to_workpiece_w, 1),
                    "contact_time_ms": round(contact_time_s * 1000, 3),
                    "heat_flux_w_per_m2": round(heat_flux_w_per_m2, 0),
                    "feed_per_tooth_mm": round(feed_per_tooth, 4),
                    "rubbing_detected": rubbing,
                    "dust_collection_active": ctx.use_dust_collection,
                    "thermal_conductivity": k_thermal,
                    "burn_tendency": burn_tendency,
                },
            )

        except (ZeroDivisionError, ValueError, TypeError, ArithmeticError, OverflowError) as e:  # WP-1: narrowed from except Exception
            return SawCalculatorResult(
                calculator_name="heat",
                score=50.0,
                warning=f"Heat calculation error: {str(e)}",
            )
