# app/cam/post_processor.py

"""
CNC Post-Processor Module (LP-GAP-06)

Provides standardized G-code generation for tool changes, tool compensation,
and cutter compensation across all CAM modules.

Features:
- G43 tool length compensation (automatic after M6)
- G41/G42 cutter radius compensation (climb/conventional)
- Tool change sequencing with optional M0/M1 pauses
- Controller-specific dialect support (GRBL, Mach3, Haas, LinuxCNC)

Usage:
    from app.cam.post_processor import PostProcessor, PostConfig

    config = PostConfig(
        emit_tool_length_comp=True,
        emit_cutter_comp=True,
        tool_change_pause="M1",  # Optional stop
    )
    post = PostProcessor(config)

    # Generate tool change with G43
    lines = post.tool_change(tool_number=1, rpm=18000, tool_name="1/2 Ball End")

    # Generate cutter comp start (G41 for climb milling)
    lines = post.cutter_comp_start(tool_diameter_mm=12.7, climb=True)

    # Generate cutter comp cancel
    lines = post.cutter_comp_cancel()
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional, Literal


class ToolChangeMode(str, Enum):
    """Tool change pause behavior."""
    NONE = "none"           # No pause - automatic tool changer
    M0 = "M0"               # Mandatory stop (operator intervention)
    M1 = "M1"               # Optional stop (can be skipped via panel)
    DWELL = "dwell"         # Short dwell only (G4)


class CutterCompMode(str, Enum):
    """Cutter compensation modes."""
    OFF = "off"             # No cutter comp (pre-calculated offsets)
    G41 = "G41"             # Cutter comp left (climb milling)
    G42 = "G42"             # Cutter comp right (conventional milling)


@dataclass
class PostConfig:
    """
    Post-processor configuration.

    Attributes:
        emit_tool_length_comp: If True, emit G43 Hn after each M6
        emit_cutter_comp: If True, emit G41/G42 for profiling operations
        tool_change_pause: Pause mode after tool changes
        dwell_after_spindle_ms: Dwell time after spindle start (ms)
        safe_z_mm: Safe Z height for tool changes
        use_h_equals_t: If True, use H = T (G43 H1 for T1). If False, allow different H.
        controller: Target controller (affects G-code dialect)
    """
    emit_tool_length_comp: bool = True
    emit_cutter_comp: bool = False
    tool_change_pause: ToolChangeMode = ToolChangeMode.NONE
    dwell_after_spindle_ms: int = 2000
    safe_z_mm: float = 50.0
    use_h_equals_t: bool = True
    controller: Literal["GRBL", "Mach3", "Haas", "LinuxCNC", "Fanuc"] = "GRBL"

    # Cutter comp settings
    cutter_comp_approach_mm: float = 3.0  # Lead-in distance for G41/G42
    cutter_comp_lead_angle_deg: float = 45.0  # Lead-in angle


@dataclass
class ToolSpec:
    """Tool specification for post-processor operations."""
    tool_number: int
    name: str = ""
    diameter_mm: float = 6.35
    rpm: int = 18000
    offset_number: Optional[int] = None  # H register (defaults to tool_number)

    @property
    def h_number(self) -> int:
        """Get H register number (tool length offset)."""
        return self.offset_number if self.offset_number is not None else self.tool_number

    @property
    def d_number(self) -> int:
        """Get D register number (cutter radius offset)."""
        return self.offset_number if self.offset_number is not None else self.tool_number


class PostProcessor:
    """
    CNC Post-Processor for standardized G-code generation.

    Handles:
    - Tool changes with G43 tool length compensation
    - Cutter radius compensation (G41/G42)
    - Controller-specific dialect adaptations
    """

    def __init__(self, config: Optional[PostConfig] = None):
        self.config = config or PostConfig()
        self._current_tool: Optional[ToolSpec] = None
        self._cutter_comp_active: bool = False

    # =========================================================================
    # PROGRAM STRUCTURE
    # =========================================================================

    def program_header(
        self,
        program_name: str = "CNC Program",
        units: Literal["mm", "inch"] = "mm",
        work_offset: str = "G54",
    ) -> List[str]:
        """
        Generate program header with safety block.

        Args:
            program_name: Program identifier
            units: G21 (mm) or G20 (inch)
            work_offset: Work coordinate system (G54-G59)

        Returns:
            List of G-code lines
        """
        unit_code = "G21" if units == "mm" else "G20"

        lines = [
            f"( {program_name} )",
            f"( Generated by Luthier's ToolBox )",
            "",
            "( Safety Block )",
            f"{unit_code}",       # Units
            "G90",               # Absolute positioning
            "G17",               # XY plane
            "G40",               # Cancel cutter comp
            "G49",               # Cancel tool length comp
            "G80",               # Cancel canned cycles
            f"{work_offset}",    # Work coordinate system
            "",
        ]

        # Add path blending for LinuxCNC
        if self.config.controller == "LinuxCNC":
            lines.insert(-1, "G64 P0.05")  # Path blending with 0.05mm tolerance

        return lines

    def program_footer(self) -> List[str]:
        """
        Generate program footer with safe end sequence.

        Returns:
            List of G-code lines
        """
        lines = [
            "",
            "( Program End )",
            "G40",               # Cancel cutter comp
            "G49",               # Cancel tool length comp
            "M5",                # Spindle off
            "M9",                # Coolant off
            f"G0 Z{self.config.safe_z_mm:.3f}",  # Retract
            "G28 G91 Z0",        # Return to machine Z zero (incremental)
            "G90",               # Back to absolute
            "M30",               # Program end + rewind
        ]
        return lines

    # =========================================================================
    # TOOL CHANGES (G43 TOOL LENGTH COMPENSATION)
    # =========================================================================

    def tool_change(
        self,
        tool: Optional[ToolSpec] = None,
        tool_number: Optional[int] = None,
        rpm: Optional[int] = None,
        tool_name: str = "",
    ) -> List[str]:
        """
        Generate tool change sequence with G43 tool length compensation.

        Args:
            tool: ToolSpec object (preferred)
            tool_number: Tool number (if tool not provided)
            rpm: Spindle RPM (if tool not provided)
            tool_name: Tool description (if tool not provided)

        Returns:
            List of G-code lines including:
            - Comment with tool name
            - Spindle stop
            - Tool change (M6)
            - G43 tool length comp (if enabled)
            - Spindle start
            - Optional pause (M0/M1)
            - Dwell
            - Retract to safe Z

        Example Output:
            ( Tool Change: T1 - 1/2" Ball End )
            M5
            T1 M6
            G43 H1
            S18000 M3
            M1
            G4 P2000
            G0 Z50.000
        """
        if tool is None:
            if tool_number is None:
                raise ValueError("Either tool or tool_number must be provided")
            tool = ToolSpec(
                tool_number=tool_number,
                name=tool_name,
                rpm=rpm or 18000,
            )

        self._current_tool = tool

        lines = [
            "",
            f"( Tool Change: T{tool.tool_number} - {tool.name} )" if tool.name else f"( Tool Change: T{tool.tool_number} )",
        ]

        # Spindle off
        lines.append("M5")

        # Tool change
        lines.append(f"T{tool.tool_number} M6")

        # Tool length compensation (G43)
        if self.config.emit_tool_length_comp:
            lines.append(f"G43 H{tool.h_number}")

        # Spindle start
        lines.append(f"S{tool.rpm} M3")

        # Optional pause
        if self.config.tool_change_pause == ToolChangeMode.M0:
            lines.append("M0  ( Mandatory stop - check tool )")
        elif self.config.tool_change_pause == ToolChangeMode.M1:
            lines.append("M1  ( Optional stop - verify tool change )")

        # Dwell for spindle ramp-up
        if self.config.dwell_after_spindle_ms > 0:
            dwell = self._format_dwell(self.config.dwell_after_spindle_ms)
            lines.append(dwell)

        # Retract to safe Z
        lines.append(f"G0 Z{self.config.safe_z_mm:.3f}")

        return lines

    def cancel_tool_length_comp(self) -> List[str]:
        """
        Cancel tool length compensation (G49).

        Returns:
            List of G-code lines
        """
        return ["G49  ( Cancel tool length comp )"]

    # =========================================================================
    # CUTTER COMPENSATION (G41/G42)
    # =========================================================================

    def cutter_comp_left(
        self,
        tool: Optional[ToolSpec] = None,
    ) -> List[str]:
        """
        Enable cutter compensation left (G41) for climb milling.

        G41 offsets the tool path to the LEFT of the programmed path,
        which is correct for climb milling (tool moves in same direction
        as feed along the cut).

        Args:
            tool: Tool specification (uses current tool if None)

        Returns:
            List of G-code lines

        Note:
            Must be followed by a lead-in move before cutting!
            The controller needs at least one linear move to establish
            the compensation direction.
        """
        tool = tool or self._current_tool
        if tool is None:
            raise ValueError("No tool specified for cutter compensation")

        self._cutter_comp_active = True

        return [
            f"G41 D{tool.d_number}  ( Cutter comp left - climb milling )",
        ]

    def cutter_comp_right(
        self,
        tool: Optional[ToolSpec] = None,
    ) -> List[str]:
        """
        Enable cutter compensation right (G42) for conventional milling.

        G42 offsets the tool path to the RIGHT of the programmed path,
        which is correct for conventional milling (tool moves opposite
        to feed direction along the cut).

        Args:
            tool: Tool specification (uses current tool if None)

        Returns:
            List of G-code lines
        """
        tool = tool or self._current_tool
        if tool is None:
            raise ValueError("No tool specified for cutter compensation")

        self._cutter_comp_active = True

        return [
            f"G42 D{tool.d_number}  ( Cutter comp right - conventional milling )",
        ]

    def cutter_comp_cancel(self) -> List[str]:
        """
        Cancel cutter compensation (G40).

        Returns:
            List of G-code lines

        Note:
            Should be called before tool changes, rapid moves to
            different areas, or program end.
        """
        self._cutter_comp_active = False
        return ["G40  ( Cancel cutter comp )"]

    def cutter_comp_start(
        self,
        climb: bool = True,
        tool: Optional[ToolSpec] = None,
    ) -> List[str]:
        """
        Start cutter compensation (convenience method).

        Args:
            climb: True for climb milling (G41), False for conventional (G42)
            tool: Tool specification

        Returns:
            List of G-code lines
        """
        if climb:
            return self.cutter_comp_left(tool)
        else:
            return self.cutter_comp_right(tool)

    @property
    def is_cutter_comp_active(self) -> bool:
        """Check if cutter compensation is currently active."""
        return self._cutter_comp_active

    # =========================================================================
    # HELPER METHODS
    # =========================================================================

    def _format_dwell(self, milliseconds: int) -> str:
        """
        Format dwell command for target controller.

        Args:
            milliseconds: Dwell time in milliseconds

        Returns:
            Formatted G4 command
        """
        if self.config.controller == "Haas":
            # Haas uses seconds
            seconds = milliseconds / 1000.0
            return f"G4 P{seconds:.3f}"
        else:
            # Most controllers use milliseconds (or interpret P as seconds with decimal)
            # GRBL and Mach3 use P in seconds with decimal
            seconds = milliseconds / 1000.0
            return f"G4 P{seconds:.1f}"

    def spindle_on(self, rpm: int, direction: Literal["CW", "CCW"] = "CW") -> List[str]:
        """
        Generate spindle start command.

        Args:
            rpm: Spindle RPM
            direction: CW (M3) or CCW (M4)

        Returns:
            List of G-code lines
        """
        m_code = "M3" if direction == "CW" else "M4"
        return [f"S{rpm} {m_code}"]

    def spindle_off(self) -> List[str]:
        """Generate spindle stop command."""
        return ["M5"]

    def coolant_on(self, mode: Literal["flood", "mist", "both"] = "flood") -> List[str]:
        """
        Generate coolant start command.

        Args:
            mode: flood (M8), mist (M7), or both (M7 M8)

        Returns:
            List of G-code lines
        """
        if mode == "flood":
            return ["M8  ( Flood coolant on )"]
        elif mode == "mist":
            return ["M7  ( Mist coolant on )"]
        else:
            return ["M7 M8  ( Mist + flood coolant on )"]

    def coolant_off(self) -> List[str]:
        """Generate coolant stop command."""
        return ["M9  ( Coolant off )"]

    def comment(self, text: str) -> List[str]:
        """Generate a comment line."""
        return [f"( {text} )"]

    def rapid_z(self, z_mm: float) -> List[str]:
        """Generate rapid Z move."""
        return [f"G0 Z{z_mm:.3f}"]

    def safe_retract(self) -> List[str]:
        """Retract to safe Z height."""
        return [f"G0 Z{self.config.safe_z_mm:.3f}"]


# =============================================================================
# CONVENIENCE FUNCTIONS
# =============================================================================

def generate_tool_change(
    tool_number: int,
    rpm: int,
    tool_name: str = "",
    emit_g43: bool = True,
    pause_mode: ToolChangeMode = ToolChangeMode.NONE,
    dwell_ms: int = 2000,
    safe_z_mm: float = 50.0,
) -> List[str]:
    """
    Convenience function to generate a tool change sequence.

    Args:
        tool_number: Tool number (T register)
        rpm: Spindle RPM
        tool_name: Tool description for comment
        emit_g43: If True, emit G43 Hn after M6
        pause_mode: Optional M0/M1 pause
        dwell_ms: Spindle ramp-up dwell in milliseconds
        safe_z_mm: Safe Z retract height

    Returns:
        List of G-code lines

    Example:
        >>> lines = generate_tool_change(
        ...     tool_number=1,
        ...     rpm=18000,
        ...     tool_name="1/2 Ball End",
        ...     emit_g43=True,
        ...     pause_mode=ToolChangeMode.M1,
        ... )
    """
    config = PostConfig(
        emit_tool_length_comp=emit_g43,
        tool_change_pause=pause_mode,
        dwell_after_spindle_ms=dwell_ms,
        safe_z_mm=safe_z_mm,
    )
    post = PostProcessor(config)
    return post.tool_change(
        tool_number=tool_number,
        rpm=rpm,
        tool_name=tool_name,
    )


def generate_cutter_comp_sequence(
    climb: bool,
    tool_number: int,
) -> tuple[List[str], List[str]]:
    """
    Generate cutter compensation start and cancel sequences.

    Args:
        climb: True for climb milling (G41), False for conventional (G42)
        tool_number: Tool number for D register

    Returns:
        Tuple of (start_lines, cancel_lines)
    """
    config = PostConfig(emit_cutter_comp=True)
    post = PostProcessor(config)
    tool = ToolSpec(tool_number=tool_number)

    start = post.cutter_comp_start(climb=climb, tool=tool)
    cancel = post.cutter_comp_cancel()

    return start, cancel
