from fastapi import FastAPI, HTTPException, Request, Response
from typing import Dict, Any
import uuid, datetime, hashlib, json

app = FastAPI(title="Mock RMOS Server")

REQUEST_ID_HEADER = "X-Request-Id"

def now_utc():
    return datetime.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"

def canonical_hash(obj: Any) -> str:
    s = json.dumps(obj, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(s.encode("utf-8")).hexdigest()

@app.middleware("http")
async def request_id_middleware(request: Request, call_next):
    rid = request.headers.get(REQUEST_ID_HEADER) or str(uuid.uuid4())
    response: Response = await call_next(request)
    response.headers[REQUEST_ID_HEADER] = rid
    return response

@app.post("/ai/advisories/request")
async def request_advisory(packet: Dict[str, Any]):
    # minimal validation
    if packet.get("schema_id") != "ai_context_packet_v1":
        raise HTTPException(
            status_code=422,
            detail={"error": "SCHEMA", "message": "Invalid schema_id", "field": "schema_id"},
        )

    debug = packet.get("request", {}).get("debug", {})
    if isinstance(debug, dict):
        fe = debug.get("force_error")
        if fe == "SCHEMA":
            raise HTTPException(422, detail={"error": "AI_INTEGRATOR_SCHEMA", "message": "Mock schema error"})
        if fe == "GOVERNANCE":
            raise HTTPException(403, detail={"error": "AI_INTEGRATOR_GOVERNANCE", "message": "Mock governance error"})
        if fe == "UNSUPPORTED":
            raise HTTPException(422, detail={"error": "AI_INTEGRATOR_UNSUPPORTED", "message": "Mock unsupported"})
        if fe == "RUNTIME":
            raise HTTPException(503, detail={"error": "AI_INTEGRATOR_RUNTIME", "message": "Mock runtime error"})

    advisory_id = str(uuid.uuid4())

    artifact = {
        "schema_id": "rmos_advisory_artifact_v1",
        "advisory_id": advisory_id,
        "created_at_utc": now_utc(),
        "input": {
            "context_packet_sha256": canonical_hash(packet),
            "evidence_bundle_sha256": packet.get("evidence", {}).get("bundle_sha256"),
        },
        "engine": {
            "model_id": "mock-model",
            "template_id": packet.get("request", {}).get("template_id"),
            "template_version": packet.get("request", {}).get("template_version"),
        },
        "draft": {
            "schema_id": "advisory_draft_v1",
            "kind": "explanation",
            "content": [
                {
                    "type": "paragraph",
                    "text": "This is a mock advisory generated by the Mock RMOS Server.",
                },
                {
                    "type": "paragraph",
                    "text": "It echoes selection and evidence references without interpretation.",
                },
            ],
            "citations": packet.get("evidence", {}).get("refs", []),
        },
        "governance": {
            "status": "draft",
            "published_by": None,
            "notes": "Mock server output",
        },
    }

    return {"advisory_id": advisory_id, "artifact": artifact}
