"""
G-code generation and export.
"""

from typing import List, TextIO
from .toolpath import Toolpath


class GCodeGenerator:
    """
    Generates G-code from toolpaths.
    """

    def __init__(
        self,
        units: str = "inches",
        safe_z: float = 0.1,
        spindle_speed: int = 18000,
    ):
        """
        Initialize G-code generator.
        
        Args:
            units: 'inches' or 'mm'
            safe_z: Safe Z height for rapid moves
            spindle_speed: Spindle speed in RPM
        """
        self.units = units
        self.safe_z = safe_z
        self.spindle_speed = spindle_speed

    def generate_header(self) -> List[str]:
        """Generate G-code header."""
        lines = [
            "( Generated by Luthier's Toolbox )",
            "( CAM Module - G-code Generator )",
            "",
        ]

        # Set units
        if self.units == "inches":
            lines.append("G20 ( Inches )")
        else:
            lines.append("G21 ( Millimeters )")

        lines.extend(
            [
                "G90 ( Absolute positioning )",
                "G17 ( XY plane )",
                f"M3 S{self.spindle_speed} ( Start spindle )",
                "G4 P2 ( Wait 2 seconds for spindle to reach speed )",
                "",
            ]
        )

        return lines

    def generate_footer(self) -> List[str]:
        """Generate G-code footer."""
        return [
            "",
            f"G0 Z{self.safe_z} ( Retract to safe Z )",
            "M5 ( Stop spindle )",
            "G0 X0 Y0 ( Return to origin )",
            "M2 ( End program )",
        ]

    def generate_toolpath_gcode(self, toolpath: Toolpath) -> List[str]:
        """
        Generate G-code for a single toolpath.
        
        Args:
            toolpath: Toolpath to convert
            
        Returns:
            List of G-code lines
        """
        lines = [
            "",
            f"( Toolpath: {toolpath.name} )",
            f"( Type: {toolpath.toolpath_type.value} )",
            f"( Tool diameter: {toolpath.tool_diameter} )",
            f"( Feedrate: {toolpath.feedrate} )",
            "",
        ]

        # Set feedrate
        lines.append(f"F{toolpath.feedrate}")

        for i, (x, y, z) in enumerate(toolpath.points):
            if i == 0:
                # First move - rapid to position
                lines.append(f"G0 X{x:.4f} Y{y:.4f} Z{self.safe_z:.4f}")
            elif z > -0.001:
                # Above surface - rapid move
                lines.append(f"G0 X{x:.4f} Y{y:.4f} Z{z:.4f}")
            else:
                # Cutting move
                lines.append(f"G1 X{x:.4f} Y{y:.4f} Z{z:.4f}")

        # Retract at end
        if toolpath.points:
            last_x, last_y, _ = toolpath.points[-1]
            lines.append(f"G0 Z{self.safe_z:.4f}")

        return lines

    def generate(self, toolpaths: List[Toolpath]) -> str:
        """
        Generate complete G-code program.
        
        Args:
            toolpaths: List of toolpaths to convert
            
        Returns:
            Complete G-code program as string
        """
        lines = []

        # Add header
        lines.extend(self.generate_header())

        # Add each toolpath
        for toolpath in toolpaths:
            lines.extend(self.generate_toolpath_gcode(toolpath))

        # Add footer
        lines.extend(self.generate_footer())

        return "\n".join(lines)


class GCodeExporter:
    """
    Exports G-code to files.
    """

    def __init__(self, generator: GCodeGenerator):
        """
        Initialize exporter.
        
        Args:
            generator: G-code generator to use
        """
        self.generator = generator

    def export(self, toolpaths: List[Toolpath], filename: str) -> None:
        """
        Export toolpaths to G-code file.
        
        Args:
            toolpaths: Toolpaths to export
            filename: Output filename
        """
        gcode = self.generator.generate(toolpaths)

        with open(filename, "w") as f:
            f.write(gcode)

    def export_with_stats(
        self, toolpaths: List[Toolpath], filename: str
    ) -> dict:
        """
        Export G-code and return statistics.
        
        Args:
            toolpaths: Toolpaths to export
            filename: Output filename
            
        Returns:
            Dictionary with export statistics
        """
        self.export(toolpaths, filename)

        # Calculate statistics
        total_points = sum(len(tp.points) for tp in toolpaths)
        total_time = sum(tp.get_estimated_time() for tp in toolpaths)

        return {
            "toolpaths": len(toolpaths),
            "total_points": total_points,
            "estimated_time_minutes": total_time,
            "file": filename,
        }
