/**
 * Acoustic State Utilities
 *
 * Dev Order 15: Helper functions for creating and working with AcousticState.
 */

import type {
  AcousticState,
  ApertureGeometryLike,
} from '@/types/acoustics'

/**
 * Default assumptions for geometry-derived acoustic state.
 */
const DEFAULT_GEOMETRY_ASSUMPTIONS: string[] = [
  'Geometry-derived state only',
  'No body volume attached',
  'No calibrated acoustic model applied',
  'No measured response data attached',
]

/**
 * Create an acoustic state from aperture geometry.
 *
 * This creates a low-confidence, geometry-estimate state.
 * It does not compute acoustic predictions - it scaffolds the
 * acoustic state for future solver integration.
 */
export function createGeometryAcousticState(params: {
  id: string
  label: string
  apertureGeometry: ApertureGeometryLike
  bodyVolumeLiters?: number
  assumptions?: string[]
  warnings?: string[]
}): AcousticState {
  const {
    id,
    label,
    apertureGeometry,
    bodyVolumeLiters,
    assumptions = [],
    warnings,
  } = params

  // Merge default assumptions with any custom ones
  const mergedAssumptions = [
    ...DEFAULT_GEOMETRY_ASSUMPTIONS.filter(
      (a) => !assumptions.some((custom) => custom.toLowerCase().includes(a.toLowerCase().split(' ')[0]))
    ),
    ...assumptions,
  ]

  // If body volume is provided, remove the "No body volume attached" assumption
  const finalAssumptions = bodyVolumeLiters
    ? mergedAssumptions.filter((a) => !a.includes('No body volume'))
    : mergedAssumptions

  return {
    id,
    label,
    source: 'geometry_estimate',
    confidence: 'low',
    apertureType: apertureGeometry.aperture_type,
    apertureGeometry,
    bodyVolumeLiters,
    assumptions: finalAssumptions,
    warnings,
  }
}

/**
 * Check if an acoustic state has any estimated acoustic values.
 *
 * Returns true if any of the acoustic estimate fields are present:
 * - estimatedHelmholtzHz
 * - estimatedEffectiveLengthMm
 * - qEstimate
 * - lossEstimate
 */
export function hasEstimatedAcoustics(state: AcousticState): boolean {
  return (
    state.estimatedHelmholtzHz !== undefined ||
    state.estimatedEffectiveLengthMm !== undefined ||
    state.qEstimate !== undefined ||
    state.lossEstimate !== undefined
  )
}

/**
 * Get a human-readable confidence label.
 */
export function getConfidenceLabel(confidence: AcousticState['confidence']): string {
  switch (confidence) {
    case 'high':
      return 'High'
    case 'medium':
      return 'Medium'
    case 'low':
      return 'Low'
    case 'unknown':
    default:
      return 'Unknown'
  }
}

/**
 * Get a human-readable source label.
 */
export function getSourceLabel(source: AcousticState['source']): string {
  switch (source) {
    case 'geometry_estimate':
      return 'Geometry Estimate'
    case 'measured':
      return 'Measured'
    case 'calibrated':
      return 'Calibrated'
    case 'manual':
      return 'Manual Entry'
    case 'unknown':
    default:
      return 'Unknown'
  }
}

/**
 * Default assumptions for manual estimate attachment.
 */
const MANUAL_ESTIMATE_ASSUMPTIONS: string[] = [
  'Manual estimate attached by user',
  'No calibrated acoustic model applied',
  'Estimate is not generated by the system',
]

/**
 * Merge manual estimates into an existing acoustic state.
 * Dev Order 24: Preserves geometry, updates estimates, sets source to manual.
 */
export function mergeManualEstimates(
  baseState: AcousticState,
  estimates: {
    estimatedHelmholtzHz?: number
    estimatedEffectiveLengthMm?: number
    qEstimate?: number
    lossEstimate?: number
  }
): AcousticState {
  const hasAnyEstimate =
    estimates.estimatedHelmholtzHz !== undefined ||
    estimates.estimatedEffectiveLengthMm !== undefined ||
    estimates.qEstimate !== undefined ||
    estimates.lossEstimate !== undefined

  if (!hasAnyEstimate) {
    return baseState
  }

  return {
    ...baseState,
    source: 'manual',
    confidence: 'low',
    estimatedHelmholtzHz: estimates.estimatedHelmholtzHz,
    estimatedEffectiveLengthMm: estimates.estimatedEffectiveLengthMm,
    qEstimate: estimates.qEstimate,
    lossEstimate: estimates.lossEstimate,
    assumptions: MANUAL_ESTIMATE_ASSUMPTIONS,
    warnings: baseState.warnings,
  }
}

/**
 * Update geometry fields in an acoustic state while preserving manual estimates.
 * Dev Order 24: Called when geometry changes but estimates should persist.
 */
export function updateGeometryPreservingEstimates(
  currentState: AcousticState,
  newGeometryState: AcousticState
): AcousticState {
  const hasManualEstimates = currentState.source === 'manual' && hasEstimatedAcoustics(currentState)

  if (!hasManualEstimates) {
    return newGeometryState
  }

  // Preserve manual estimates, update geometry, add stale warning
  const warnings = [
    ...(currentState.warnings ?? []).filter(
      (w) => !w.includes('Geometry has changed since')
    ),
    'Geometry has changed since this manual estimate was attached. Re-check whether the estimate still applies.',
  ]

  return {
    ...newGeometryState,
    source: 'manual',
    confidence: 'low',
    estimatedHelmholtzHz: currentState.estimatedHelmholtzHz,
    estimatedEffectiveLengthMm: currentState.estimatedEffectiveLengthMm,
    qEstimate: currentState.qEstimate,
    lossEstimate: currentState.lossEstimate,
    assumptions: currentState.assumptions,
    warnings,
  }
}
